# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    lint:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v1
        - name: Setup Python Environment
          uses: actions/setup-python@v1.1.1
        - name: Install Requirements
          run: pip install --quiet --requirement requirements.txt
        - name: Lint Code
          run: |
            flake8 --ignore=E501,E231 *.py
            pylint --disable=C0301 --disable=C0326 *.py
        - name: Run unit tests
          run: |
            python -m unittest --verbose --failfast
#   job1:
#     name: First job
#     runs-on: ubuntu-latest
#     steps:
#       - name: Step one
#         uses: actions/checkout@v2
#       - name: Step two
#         run: env | sort
#       - name: Python Syntax Checker
#         # You may pin to the exact commit or the version.
#         # uses: cclauss/Find-Python-syntax-errors-action@90f67be9fb626b675a3971b1d08ab29851cb721f
#         uses: cclauss/Find-Python-syntax-errors-action@v0.2.0

#   job2:
#     name: Second job
#     runs-on: windows-latest
#     steps:
#       - name: Step one
#         uses: actions/checkout@v2
#       - name: Step two
#         run: "Get-ChildItem Env: | Sort-Object Name"

#   job3:
#     name: Third job
#     needs: [job1, job2]
#     runs-on: windows-latest
#     steps:
#       - run: "Get-ChildItem Env: | Sort-Object Name"
    
