# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: env | sort

  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name"

  job3:
  name: Third job
  runs-on: windows-latest
  steps:
    - needs: [job1, job2]
